= Parameters

The parent key for all of the following parameters is `nfs_subdir_external_provisioner`.

== `namespace`

[horizontal]
type:: string
default:: `syn-nfs-subdir-external-provisioner`

The namespace in which to deploy this component.


== `release_name`

[horizontal]
type:: string
default:: `${_instance}`

The name syn-nfs-subdir-external-provisioner is deployed.
By default, the commodore meta-parameter `parameters._instance` is used. `parameters._instance` is set to the aliased name used for instantiation or the component name for non-aliased instances.


== `charts.nfs_subdir_external_provisioner`

[horizontal]
type:: string
default:: See https://github.com/projectsyn/component-nfs-subdir-external-provisioner/blob/master/class/defaults.yml[class/defaults.yml]

The helm chart version going to be used.


== `helm_values`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
storageClass:
  accessModes: ReadWriteMany
----

All helm_values are passed to the helm chart.
This allows to configure all https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/tree/master/charts/nfs-subdir-external-provisioner#configuration[nfs-subdir-external-provisioner helm chart values].
